<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="Painel Administrativo" />
	<meta name="author" content="Hudson Nicoletti" />

	<title>Painel Administrativo </title>

	<?php echo $this->assets->outputCss(); ?>

</head>
    <body class="page-body <?php echo ($this->router->getControllerName() == 'login' ? 'login-page' : '' ); ?>">

    <?php if($this->router->getControllerName() != 'login'): ?>
    <nav class="navbar horizontal-menu navbar-fixed-top navbar-minimal"><!-- set fixed position by adding class "navbar-fixed-top" -->

		<div class="navbar-inner">

			<!-- Navbar Brand -->
			<div class="navbar-brand">
				<a href="/" class="logo">
					<img src="/assets/public/images/logo.png" height="48" alt="" class="hidden-xs" />
					<img src="/assets/public/images/logo.png" height="48" alt="" class="visible-xs" />
				</a>
			</div>

			<!-- Mobile Toggles Links -->
			<div class="nav navbar-mobile">

				<!-- This will toggle the mobile menu and will be visible only on mobile devices -->
				<div class="mobile-menu-toggle">
					<a href="#" data-toggle="mobile-menu-horizontal">
						<i class="fa-bars"></i>
					</a>
				</div>

			</div>

			<div class="navbar-mobile-clear"></div>


			<ul class="navbar-nav">
        <li>
          <a href="/admin/index">
            <i class="fa-home"></i>
            <span class="title">Visão Geral</span>
          </a>
        </li>
        <li>
          <a href="/admin/gallery">
            <i class="fa-photo"></i>
            <span class="title">Galeria</span>
          </a>
        </li>
        <li>
          <a href="/admin/tips">
            <i class="fa-lightbulb-o"></i>
            <span class="title">Dicas</span>
          </a>
        </li>
      </ul>


			<!-- notifications and other links -->
			<ul class="nav nav-userinfo navbar-right">


				<li class="dropdown user-profile">
						<a href="#" data-toggle="dropdown">
							<span>
								<?php echo $current_user->name; ?>
								<i class="fa-angle-down"></i>
							</span>
						</a>

						<ul class="dropdown-menu user-profile-menu list-unstyled">
							<li>
								<a href="/admin/settings">
									<i class="fa-cog"></i>
									Configurações
								</a>
							</li>

							<li>
								<a href="/admin/logout">
									<i class="fa-lock"></i>
									Logout
								</a>
							</li>
						</ul>
					</li>

			</ul>

		</div>

	</nav>
    <?php endif; ?>

    <?php echo $this->getContent(); ?>
    </body>
    <?php echo $this->assets->outputJs(); ?>

</html>
