<div class="page-container">
  <div class="main-content">
    <div class="row">

      <div class="col-sm-12">
          <a href="/admin/tips/new">
              <button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right">
                <i class="fa-plus"></i><span>Adicionar Dica</span>
              </button>
          </a>
      </div>

      <div class="col-md-12">
        <div class="xe-widget xe-conversations">
          <div class="xe-bg-icon">
            <i class="fa-newspaper-o"></i>
          </div>
          <div class="xe-header">
            <div class="xe-icon">
              <i class="fa-lightbulb-o"></i>
            </div>
            <div class="xe-label">
              <h3>
                Dicas
                <small>Dicas cadastradas</small>
              </h3>
            </div>
          </div>

          <div class="xe-body">
            <input type="text" class="form-control form-focus-info full-width" id="search_wdg" placeholder="Search ... ">
            <ul class="list-unstyled" id="list-unstyled">

              <?php foreach($tips as $tip): ?>
              <li>
                <div class="xe-comment-entry">
                  <a href="/admin/tip/<?=$tip->slug;?>" class="xe-user-img">
                    <img src="/assets/public/images/tips/<?=$tip->image;?>" class="img-circle" width="100" height="100">
                  </a>
                  <div class="xe-comment">
                    <div class="col-md-9">
                      <a href="/admin/tip/<?=$tip->slug;?>" class="xe-user-name">
                        <strong><?=$tip->title;?></strong>
                      </a>
                      <div class="form-group inline">
                        <span class="badge badge-primary" style="font-size: 12px">
                          <i class="fa-clock-o"></i> <?=(new DateTime($tip->date))->format("d/m/Y \a\s H:i");?>
                        </span>
                      </div>
                    </div>
                    <div class="col-md-3">
                      <form class="inline-form" action="/admin/tip/remove/<?=$tip->slug;?>" method="post" role="form">
                        <?php echo $form->render("security"); ?>
                        <button type="submit"class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                      </form>
                      <a href="/admin/tip/<?=$tip->slug;?>">
                        <button class="btn btn-info btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-pencil"></i><span>Alterar</span></button>
                      </a>
                    </div>
                  </div>
                </div>
              </li>
              <?php endforeach; ?>
            </ul>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
