<div class="page-container">

    <div class="main-content">

        <div class="row">
<!--
            <div class="col-sm-12">
                <a href="/services/create/"><button class="btn btn-secondary btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-plus"></i><span>Adicionar</span></button></a>
            </div>
-->

            <div class="col-sm-12">

				<div class="xe-widget xe-conversations">
                    <div class="xe-bg-icon">
                        <i class="fa-send"></i>
                    </div>
                    <div class="xe-header">
                        <div class="xe-icon">
                            <i class="fa-send"></i>
                        </div>
                        <div class="xe-label">
                            <h3>
                                Assinaturas de Newsletter
                                <small>Lista de assinatura eletrônicas para receber novidades.</small>
                            </h3>
                            <form class="inline-form" action="/admin/newsletter/list" method="post" role="form">
                              <?php echo $form->render("security"); ?>
                              <button type="submit" class="btn btn-success btn-icon btn-sm btn-icon-standalone btn-icon-standalone-right pull-right">
                                <i class="fa-download"></i><span>Baixar Lista</span>
                              </button>
                            </form>
                        </div>
                    </div>

                    <div class="xe-body">
                        <ul class="list-unstyled" id="list-unstyled">
                            <?php foreach($newsletters as $newsletter): ?>
                            <li>
                                <div class="xe-comment-entry">
                                    <div class="xe-comment">

                                      <div class="col-lg-10 col-md-9 col-sm-12">
                                        <a href="/services/edit/0" class="xe-user-name">
                                          <strong><?=$newsletter->email;?></strong>
                                          <span class="badge badge-green"><?=(new DateTime($newsletter->date))->format("d-m-Y \a\s H:i:s");?></span>
                                        </a>
                                      </div>

                                      <div class="col-lg-2 col-md-3 col-sm-12 text-right">
                                        <form class="inline-form" action="/admin/newsletter/remove/<?=$newsletter->_;?>" method="post" role="form">
                                          <?php echo $form->render("security"); ?>
                                          <button type="submit"class="btn btn-danger btn-icon btn-icon-standalone btn-icon-standalone-right pull-right"><i class="fa-close"></i><span>Remover</span></button>
                                        </form>
                                      </div>

                                    </div>

                                </div>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
<!--
						<div class="xe-footer">
							<a href="#">View All</a>
						</div>
-->
                </div>

            </div>
        </div>
    </div>
</div>
