<section data-scroll-index="1" class="tips">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Dicas</h2>
    </div>
    <div class="articles">

      <?php foreach ($tips as $tip): ?>
      <article>
        <figure>
          <img src="assets/public/images/tips/<?php echo $tip->image; ?>" alt="<?php echo $tip->title; ?>">
        </figure>
        <p><?php echo $tip->title; ?></p>
        <a href="/dica/<?php echo $tip->slug; ?>">ler mais</a>
      </article>
      <?php endforeach; ?>

    </div>
    <div class="pagination" id="pagination">

    </div>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
