<section data-scroll-index="1" class="tip-info">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2><?php echo $tip->title; ?></h2>
    </div>

    <article>
      <figure>
        <img src="/assets/public/images/tips/<?php echo $tip->image; ?>" alt="<?php echo $tip->title; ?>">
      </figure>
      <div class="text"><?php echo $tip->text; ?></div>
    </article>

    <a href="<?php echo $tip->font; ?>" class="font">Fonte aqui</a>
    <div class="social">
      <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
    </div>

  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
