<section data-scroll-index="1" class="about">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Instalação</h2>
      <p>O condicionamento de ar é um processo de tratamento do ar interior de espaços fechados.</p>
      <p>Este tratamento tem por finalidade, fazer ajustes nos ambientes alterando desta forma a qualidade do ar interior, no que diz respeito às suas condições de temperatura, umidade, limpeza e movimentação do ar. Para tal, um sistema de condicionamento de ar contém funções como; Aquecimento, Arrefecimento (baixa da temperatura), Umidificação, Renovação (admissão de ar externo), Filtragem e Ventilação do ar.</p>
      <p>Para termos um condicionamento de ar eficiente e otimizado, precisamos utilizar outros fatores que irão favorecer o baixo consumo de energia. Para que isso aconteça, podemos citar alguns exemplos, como os revestimentos térmicos em forros e paredes (internas/externas), películas refletivas para superfícies de vidro, pé direito que favoreça uma eficiente circulação de ar, lâmpadas de LED, superfícies de lajes/forro de PVC revestidas com isopor, lã de rocha e/ou telhados com telhas de barro, manta de alumínio com polietileno termo soldado, esquadrias de PVC ou de madeira, entre outros...</p>
      <p>Olhando por outro ângulo, não basta apenas nos preocuparmos em termos um baixo consumo de energia, mas sim, fazer uso da mesma de maneira consciente, pois é a nossa atitude que poderá fazer a diferença, principalmente quando falamos de temas polêmicos como por exemplo: Poluição, Aquecimento global, matriz energética trabalhando no limite, falta de água nos mananciais, desmatamentos. Podemos observar que esses temas estão inter-relacionados e com certeza afeta a nossa qualidade de vida, por isso, chamamos a atenção para refletirmos sobre nossas atitudes e buscarmos uma sustentabilidade de forma consciente, procurando preservar ao máximo o mundo em que vivemos.</p>
      <p>A Industrias de condicionadores de ar, ao longo destes anos, tem procurado se atualizar e evoluir. Muitos estudos sobre fontes de energia renováveis, energia limpa estão em andamento, além disso, houve um significativo avanço da eletrônica, controles de automação, utilização de gases que não agridem a camada de ozônio, mudança no aspecto construtivo dos compressores (VRV, Inverter, scroll e parafuso), e dos equipamentos como um todo. Todos esses avanços, balizando a tendência de oferecer conforto e ao mesmo tempo buscar eficiência com baixo consumo de energia.</p>
      <p>Aqui no Brasil, já temos o Selo Procel vigorando, vale a pena dar uma olhada em nossas dicas.</p>

      <p>Entre em contato conosco ou deixe uma mensagem, solicitando o seu agendamento ou a nossa visita técnica, para atender com qualidade, agilidade e eficiência o seu chamado.</p>

      <figure class="img-group">
        <img src="/assets/public/images/content/inst_1.jpg" alt="">
        <img src="/assets/public/images/content/inst_2.jpg" alt="">
      </figure>
    </div>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
