<section data-scroll-index="1" class="about">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Locação</h2>
      <p>Ficamos felizes em poder oferecer comodidade e conforto, para o seu evento ou seu negócio. Dispomos de uma variada gama de equipamentos do tipo Split, que com certeza poderá atender a sua necessidade.
Além de locarmos os equipamentos, poderemos prover também a Instalação dos mesmos, juntamente com os Kits que se fazem necessários, para garantir a entrega dos Equipamentos em pleno funcionamento.
De maneira prática e descomplicada para fecharmos o Contrato de Locação, colocamo-nos à sua disposição para analisarmos a sua demanda e sugerir uma ótima opção de negócio.
Por isso, não perca mais tempo, entre em contato conosco ou deixe sua mensagem, teremos imenso prazer em irmos até você.
</p>
    </div>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
