<section data-scroll-index="1" class="about">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Locação</h2>
      <p>Ficamos felizes em poder oferecer comodidade e conforto, para o seu evento ou seu negócio. Dispomos de uma variada gama de equipamentos do tipo Split, que com certeza poderá atender a sua necessidade.</p>
      <p>Além de locarmos os equipamentos, poderemos prover também a Instalação dos mesmos, juntamente com os Kits que se fazem necessários, para garantir a entrega dos Equipamentos em pleno funcionamento.</p>
      <p>De maneira prática e descomplicada para fecharmos o Contrato de Locação, colocamo-nos à sua disposição para analisarmos a sua demanda e sugerir uma ótima opção de negócio.</p>
      <p>Por isso, não perca mais tempo, entre em contato conosco ou deixe sua mensagem, teremos imenso prazer em irmos até você.</p>
      <br><br>

      <h4><b>AR CONDICIONADO JANELA</b></h4>
      <p>Estamos falando de um Equipamento que está no mercado há muitos anos, com grande aceitação por seus usuários, assim sendo, um dos mais tradicionais. Um dos seus pontos fortes e manter no mesmo gabinete o EVAPORADOR e o CONDENSADOR, facilitando sua instalação.</p>
      <p>Na maioria das construções prediais já existe os lugares apropriados para sua colocação, sem necessidade de alteração de fachada.</p>
      <p>O ar de janela e um aparelho compacto, econômico e com modelos, mecânico (acionamento manual ) e eletrônico (com controle remoto digital)</p>
      <ul>
        <h4><b>Capacidades:</b></h4>
        <li>[7500 BTU/H]</li>
        <li>[10000 BTU/H]</li>
        <li>[12000 BTU/H]</li>
        <li>[18000 BTU/H]</li>
        <li>[19000 BTU/H]</li>
        <li>[21000 BTU/H]</li>
        <li>[30000 BTU/H]</li>
      </ul>
      <figure class="img-group">
        <img src="/assets/public/images/content/ar_janela.jpg" class="normal">
      </figure>


      <br><br>
      <h4><b>AR CONDICIONADO SPLIT Hi-Wall / Piso Teto</b></h4>
      <p>O ar condicionado SPLIT apresenta uma gama de opções para instalação, são utilizados em diversos tipos de ambientes, por serem modernos, discretos e com baixo nível de ruído.</p>
      <p>Os modelos do tipo Split possuem, o evaporador (unidade interna) e o condensador (unidade externa) separados, e, se interligam através de tubulações de cobre e cabeamentos elétricos, desta forma, possibilitam ser instalados a grandes distancias, facilitando a diminuição de ruídos e permitindo um ambiente refrigerado e mais agradável. Além disso a unidade interna pode ser instalada diretamente em paredes, pisos, tetos, embutidas em forros, podem receber acoplamento de rede dutos de ar. Para que haja a interligação da tubulação de cobre/elétrica, basta apenas um furo na parede, ou pequena abertura de passagem para o meio externo, conforme as condições do local ou Obra, exigirem.</p>
      <p>O modelo Piso/Teto, é excelente para climatização de ambientes de médio ou grande porte  que tenha um elevado fluxo ou aglomeração de pessoas.</p>
      <ul>
        <h4><b>Capacidades:</b></h4>
        <li>[9000 BTU/H]</li>
        <li>[12000 BTU/H]</li>
        <li>[18000 BTU/H]</li>
        <li>[24000 BTU/H]</li>
        <li>[30000 BTU/H]</li>
      </ul>
      <figure class="img-group">
        <img src="/assets/public/images/content/ar_teto.jpg" class="normal">
      </figure>

      <br><br>
      <h4><b>AR CONDICIONADO SPLIT VERTICAL</b></h4>
      <p>O Ar Condicionado Split Vertical se diferencia dos demais existentes, é também conhecido como Split Torre ou Split Coluna.</p>
      <p>Possui gabinete auto portante, a instalação da unidade interna, costuma ser fixada na parede, no piso do ambiente ou sobre bases elevadas acima do piso. Por ser de grande capacidade, este tipo de aparelho e recomendado para médios e grandes ambientes, sejam eles, residenciais ou comerciais.</p>

      <ul>
        <h4><b>Capacidades:</b></h4>
        <li>[24000 BTU/H]</li>
      </ul>
      <figure class="img-group">
        <img src="/assets/public/images/content/ar_vertical.jpg" class="normal">
      </figure>
    </div>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
