<section data-scroll-index="1" class="about">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Manutenção Preventiva</h2>
      <p>Nosso propósito é estar em consonância com as normas e diretrizes regulamentadoras                        [NBR 13.971 – Portaria do Ministério da Saúde 3.523 – Resolução ANVISA 176 & NR 09 MTE], para planejar e executar a manutenção do sistema de ar condicionado de forma cuidadosa.
A manutenção tem por finalidade manter os equipamentos e a instalação em condições normais de funcionamento mecânico e elétrico, bem como também, garantir a qualidade do ar interior. A causa principal de uma má qualidade do ar, é um efeito direto de uma manutenção inadequada.
Respeitamos e nos preocupamos com o meio ambiente, sendo assim, desde o planejamento até a execução dos serviços, fazemos a utilização de produtos biodegradáveis e com registro no Ministério da Saúde. Procuramos agir da forma mais correta possível, para que sempre estejamos no mais alto padrão de qualidade em nossa prestação de serviço, colaborando com o desenvolvimento sustentável do nosso planeta e levando conforto ao seu Ambiente.
Economize tempo e dinheiro ao planejar a sua Manutenção Preventiva, entre em contato ou deixe uma mensagem, solicitando o seu agendamento.
Lembre-se, a prevenção com seus condicionadores de ar, além de ter um baixo custo, evita despesas inesperadas com a manutenção Corretiva.</p>
      <h2>Manutenção Corretiva</h2>
      <p>
Quando ocorre uma falha ou avaria seja ela por motivo elétrico/eletrônico ou mecânico, então temos que substituir a(s) peça(s) ou componente(s) que se desgastaram ou falharam, e que levaram o equipamento a uma parada. Geralmente se faz necessário uma intervenção imediata para colocar o equipamento em operação novamente.
Recomendamos entrar em contato o mais breve possível, para que possamos analisar a causa raiz do problema e planejar o reparo de forma a causar o mínimo de transtorno.
Estamos preparados para oferecer um orçamento que cabe no seu bolso, procurando atendê-lo da melhor forma possível.
Entre em contato conosco ou deixe uma mensagem, solicitando a nossa visita, motivo pelo qual nos honra em poder servir.</p>

    </div>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
