<section data-scroll-index="1" class="about">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Multimarcas</h2>
      <p>Trabalhamos com diversas Marcas para melhor atender a sua preferência.</p>
      <p>Entre em contato conosco, utilizando nossos canais de atendimento, ou se preferir, deixe sua mensagem, teremos o maior prazer em apresentar opções de equipamentos, que farão a diferença na hora da tomada de decisão para atendimento das suas necessidades.</p>
    </div>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
