<section data-scroll-index="1" class="about">
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
  <div class="container">
    <div class="text">
      <h2>Quem Somos?</h2>
      <p>Fundada em 1990, é hoje uma Empresa Londrinense de renome e conhecida no mercado local e em várias cidades do Estado do Paraná, atuando na prestação de significativos serviços de Locação, Instalação, Manutenção Preventiva e Corretiva de equipamentos de Ar Condicionado do tipo Split System, centrais e aparelhos de Janela.</p>
      <p>Tendo mais de 26 anos de experiência, tanto na Indústria como no trato com o cliente final, de várias áreas como; Lojas em geral, bancos, órgãos governamentais, hospitais, clínicas, shopping centers, centro de exposições e eventos, entre outros...</p>
      <p>Possuímos uma equipe de profissionais gabaritados e especializados, prontos para atender a sua necessidade, de forma ágil e objetiva, oferecendo ótimas opções de Instalação e condições para locação, visando sempre superar as expectativas dos nossos clientes.</p>
      <p>Horário de Funcionamento: <br>Segunda a Sexta das 8:00 às 18:00 hs</p>
    </div>
    <figure>
      <img src="assets/public/images/content/air.png" alt="Arcolon">
    </figure>
  </div>
  <div class="border-strip"><div class="blue"></div><div class="red"></div></div>
</section>
