<section data-scroll-index="1" class="slider">
  <ul class="slides-container">
    <li style="background-image: url('assets/public/images/slider/banner-arcolon-1.jpg')">
      <div class="container center-right">
        <h2>ARCOLON</h2>
        <span>transmitindo credibilidade e confiança <br> com total dedicação e respeito a você</span>
      </div>
    </li>
    <li style="background-image: url('assets/public/images/slider/banner-arcolon-2.jpg')">
      <div class="container center-left">
        <h2>ARCOLON</h2>
        <span>sinônimo de saúde e <br>  bem-estar ao seu alcanbe</span>
      </div>
    </li>
    <li style="background-image: url('assets/public/images/slider/banner-arcolon-3.jpg')">
      <div class="container">
        <h2>ARCOLON AR-CONDICIONADO</h2>
        <span>proporcionando um clima melhor!</span>
      </div>
    </li>
  </ul>
</section>

<section data-scroll-index="2" class="about" id="about">
  <div class="container">
    <div class="text">
      <h2>Quem Somos?</h2>
      <p>Fundada em 1990, é hoje uma Empresa Londrinense de renome e conhecida no mercado local e em várias cidades do Estado do Paraná, atuando na prestação de significativos serviços de Locação, Instalação, Manutenção Preventiva e Corretiva de equipamentos de Ar Condicionado do tipo Split System, centrais e aparelhos de Janela.</p>
      <a href="/sobre">Leia Mais</a>
    </div>
    <figure>
      <img src="assets/public/images/content/air.png" alt="Arcolon">
    </figure>
  </div>
</section>

<section data-scroll-index="3" class="services" id="services">
  <div class="container">
    <h2 class="title">Serviços</h2>
    <div class="services">
      <div class="service">
        <div class="title">
          <h2 style="padding: 57px" >instalação</h2>
        </div>
        <p>O condicionamento de ar é um processo de tratamento do ar interior de espaços fechados.
        Este tratamento tem por finalidade, fazer ajustes nos ambientes alterando desta forma a qualidade do ar interior, no que diz respeito às suas condições de temperatura, umidade, limpeza e movimentação do ar.</p>
        <p>Para tal, um sistema de condicionamento de ar contém funções como; Aquecimento, Arrefecimento (baixa da temperatura), Umidificação, Renovação (admissão de ar externo), Filtragem e Ventilação do ar.</p>
        <a href="/servicos/instalacao">Leia Mais</a>
      </div>
      <div class="service">
        <div class="title">
          <h2 style="padding: 57px">locação</h2>
        </div>
        <p>Ficamos felizes em poder oferecer comodidade e conforto, para o seu evento ou seu negócio. Dispomos de uma variada gama de equipamentos do tipo Split, que com certeza poderá atender a sua necessidade.</p>
        <p>Além de locarmos os equipamentos, poderemos prover também a Instalação dos mesmos, juntamente com os Kits que se fazem necessários, para garantir a entrega dos Equipamentos em pleno funcionamento.</p>
        <a href="/servicos/locacao">Leia Mais</a>
      </div>
      <div class="service">
        <div class="title">
          <h2>manutenção preventiva e corretiva</h2>
        </div>
        <p>Nosso propósito é estar em consonância com as normas e diretrizes regulamentadoras [NBR 13.971 – Portaria do Ministério da Saúde 3.523 – Resolução ANVISA 176 &amp; NR 09 MTE], para planejar e executar a manutenção do sistema de ar condicionado de forma cuidadosa.</p>
        <p>A manutenção tem por finalidade manter os equipamentos e a instalação em condições normais de funcionamento mecânico e elétrico, bem como também, garantir a qualidade do ar interior.</p>
        <a href="/servicos/manutencao">Leia Mais</a>
      </div>
    </div>

    <div data-scroll-index="4" class="hyperlinks">
      <a class="link" href="/servicos/multimarcas">
        <h2>multimarcas</h2>
        <span><i>+</i> mais info</span>
      </a>
    </div>
  </div>


  <section data-scroll-index="5" class="gallery" id="gallery">
    <div class="container">
      <h2 class="title">Galeria</h2>
      <div class="gallery-container" id="auto-wrap">

          <?php foreach ($gallery as $image): ?>

            <figure>
              <img src="assets/public/images/content/gallery/thumbnails/<?php echo $image->image; ?>" alt="">
              <a href="assets/public/images/content/gallery/<?php echo $image->image; ?>" data-lightbox="gallery">
                <span><i>+</i> mais info</span>
              </a>
            </figure>

          <?php endforeach; ?>

      </div>
    </div>
  </section>
</section>

<section data-scroll-index="6" class="tips" id="tips">
  <div class="container">
    <h2 class="title">dicas</h2>
    <div class="tips-container">

        <?php foreach($tips as $tip): ?>
        <div class="tip">
          <img src="assets/public/images/tips/<?php echo $tip->image ?? 'default.jpg' ?>" alt="<?php echo $tip->title; ?>">
          <span>
            <p><?php echo $tip->title; ?></p>
            <a href="/dica/<?php echo $tip->slug; ?>"> Leia Mais </a>
          </span>
        </div>
        <?php endforeach; ?>

    </div>
    <a href="/dicas" class="more">Veja Mais</a>
  </div>
</section>

<section class="newsletter">
  <div class="container">
    <h2 class="title">ASSINE NOSSA NEWSLETTER</h2>
    <span class="subtitle">
      Receba nossas ultimas atualizações de serviços e promoções!
    </span>
    <form action="/newsletter/subscribe" method="post" accept-charset="utf-8" role="ajax">
      <?php echo $form->render("security"); ?>
      <input type="email" name="email" placeholder="Digite Seu E-Mail">
      <button type="submit"> Enviar ! </button>
      <br>
      <span class="result subtitle"></span>
    </form>
  </div>
</section>
