<section data-scroll-index="1" class="slider">
  <ul class="slides-container">
    <li style="background-image: url('assets/public/images/slider/banner-arcolon-1.png')"></li>
    <li style="background-image: url('assets/public/images/slider/banner-arcolon-2.png')"></li>
    <li style="background-image: url('assets/public/images/slider/banner-arcolon-3.png')"></li>
  </ul>
</section>

<section data-scroll-index="2" class="about">
  <div class="container">
    <div class="text">
      <h2>Quem Somos?</h2>
      <p>Fundada em 1990, é hoje uma Empresa Londrinense de renome e conhecida no mercado local e em várias cidades do Estado do Paraná, atuando na prestação de significativos serviços de Locação, Instalação, Manutenção Preventiva e Corretiva de equipamentos de Ar Condicionado do tipo Split System, centrais e aparelhos de Janela.</p>
      <a href="/sobre">Leia Mais</a>
    </div>
    <figure>
      <img src="assets/public/images/content/air.png" alt="Arcolon">
    </figure>
  </div>
</section>

<section data-scroll-index="3" class="services">
  <div class="container">
    <h2 class="title">Serviços</h2>
    <div class="services">
      <div class="service">
        <div class="title">
          <h2 style="padding: 57px" >instalação</h2>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo corporis, voluptas quasi ducimus repellat suscipit quam reiciendis deserunt. Eos, esse!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo corporis, voluptas quasi ducimus repellat suscipit quam reiciendis deserunt. Eos, esse!</p>
        <a href="/servicos/instalacao">Leia Mais</a>
      </div>
      <div class="service">
        <div class="title">
          <h2 style="padding: 57px">locação</h2>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo corporis, voluptas quasi ducimus repellat suscipit quam reiciendis deserunt. Eos, esse!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo corporis, voluptas quasi ducimus repellat suscipit quam reiciendis deserunt. Eos, esse!</p>
        <a href="/servicos/locacao">Leia Mais</a>
      </div>
      <div class="service">
        <div class="title">
          <h2>manutenção preventiva e corretiva</h2>
        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo corporis, voluptas quasi ducimus repellat suscipit quam reiciendis deserunt. Eos, esse!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo corporis, voluptas quasi ducimus repellat suscipit quam reiciendis deserunt. Eos, esse!</p>
        <a href="/servicos/manutencao">Leia Mais</a>
      </div>
    </div>

    <div data-scroll-index="4" class="hyperlinks">
      <a class="link" href="/servicos/multimarcas">
        <h2>multimarcas</h2>
        <span><i>+</i> mais info</span>
      </a>
    </div>
  </div>


  <section data-scroll-index="5" class="gallery">
    <div class="container">
      <h2 class="title">Galeria</h2>
      <div class="gallery-container">
        <div class="gallery-images">
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/1.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/2.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/3.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/4.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/5.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/6.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
        </div>
        <div class="gallery-images">
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/1.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/2.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/3.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/4.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/5.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/6.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
        </div>
        <div class="gallery-images">
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/1.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/2.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/3.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/4.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/5.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
          <figure>
            <img src="assets/public/images/content/gallery/thumbnails/6.jpg" alt="">
            <a href="gallery.html">
              <span><i>+</i> mais info</span>
            </a>
          </figure>
        </div>
      </div>
    </div>
  </section>
</section>

<section data-scroll-index="6" class="tips">
  <div class="container">
    <h2 class="title">dicas</h2>
    <div class="tips-container">

        <?php foreach($tips as $tip): ?>
        <div class="tip">
          <img src="assets/public/images/tips/<?php echo $tip->image ?? 'default.jpg' ?>" alt="<?php echo $tip->title; ?>">
          <span>
            <p><?php echo $tip->title; ?></p>
            <a href="/dica/<?php echo $tip->slug; ?>"> Leia Mais </a>
          </span>
        </div>
        <?php endforeach; ?>

    </div>
    <a href="/dicas" class="more">Veja Mais</a>
  </div>
</section>

<section class="newsletter">
  <div class="container">
    <h2 class="title">ASSINE NOSSA NEWSLETTER</h2>
    <span class="subtitle">
      Receba nossas ultimas atualizações de serviços e promoções!
    </span>
    <form action="/newsletter/subscribe">
      <input type="email" name="email" placeholder="Digite Seu E-Mail">
      <button type="submit"> Enviar ! </button>
    </form>
  </div>
</section>
